In [2]:
import numpy as np

In [9]:
d=5
n=3

alpha_pred = np.zeros((d,1, n))
alpha_pred

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [13]:
alpha_pred[:,:,1]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [14]:
a=np.array([[1,2],[3,4]])

a@a@a

array([[ 37,  54],
       [ 81, 118]])